{% set name = "flux-restful-client" %}
{% set version = "0.1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flux-restful-client-{{ version }}.tar.gz
  sha256: ca73fea587f301f5fb2a5c622f868011be5c0a40e68678020dd42c4726379ee3

build:
  entry_points:
    - flux-restful-cli=flux_restful_client.client:run_flux_restful_client
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pytest-runner
    - pip
  run:
    - python >=3.6
    - ruamel.yaml
    - requests
    - jsonschema
    - python-jose

test:
  imports:
    - flux_restful_client
  commands:
    - pip check
    - flux-restful-cli --help
  requires:
    - pip

about:
  home: https://github.com/flux-framework/flux-restful-api/tree/main/clients/python
  summary: Python functions and command line equivalent for interacting with Flux RESTful API.
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
